config:
  credentials:
      - id: sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      sqaaas-web:
        container: node
        commands:
          - > 
            env GIT_ASKPASS=/sqaaas-web/.git_credential_helper.sh
            npm --prefix /sqaaas-web run deploy --
            --user="David Arce <darce@i3m.upv.es>"
            --repo=https://${GIT_USER}@github.com/eosc-synergy/sqaaas-web
